name: pantora-free-viewer
version: '1.0'
summary: The Pantora AxF Viewer is 3D viewer for AxF Materials.
description: |
  The Pantora AxF Viewer is 3D viewer for AxF Materials. Pantora AxF Viewer allows users to visualize and swap 3D materials in a controlled scene with real-time rendering. No need to be an expert in computer graphics. Just drag-and-drop materials. Change the lighting to see how a material would look under different conditions.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
  - build-on: i386
base: core18

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-3-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-3-stable
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

apps:
  pantora-free-viewer:
    command: pantora-free-viewer
    desktop: usr/share/applications/pantora-free-viewer.desktop
    plugs: [ wayland, x11, opengl, home, desktop, desktop-legacy, network, hardware-observe, process-control, cups-control, removable-media, icon-themes, wine-runtime, wine-3-stable ]

parts:
  pantora-free-viewer:
    plugin: nil
    source: ./snap/local/src
    source-type: local
    override-build: |
      snapcraftctl build
      ./dl_npp
    stage:
      - bin
      - usr
      - wine-platform
      - wine-runtime
      - winedata
      - PantoraFreeViewer
    stage-packages: 
        - mesa-utils
